name: leetcode_dart
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: 3.7.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  





  
  

  
  

  

  

  
  
  
  
  
  
  
  
  
  