name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set Up Flutter
      uses: subosito/flutter-action@v2.8.0
    - name: Run Tests
      run: flutter test